[2022-06-02 09:45:11,442] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: YFinance_Crawler_DAG.CopyFromLocal 2022-06-02T09:45:00.307384+00:00 [queued]>
[2022-06-02 09:45:11,483] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: YFinance_Crawler_DAG.CopyFromLocal 2022-06-02T09:45:00.307384+00:00 [queued]>
[2022-06-02 09:45:11,483] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-06-02 09:45:11,483] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2022-06-02 09:45:11,483] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-06-02 09:45:11,512] {taskinstance.py:1038} INFO - Executing <Task(BashOperator): CopyFromLocal> on 2022-06-02T09:45:00.307384+00:00
[2022-06-02 09:45:11,515] {standard_task_runner.py:51} INFO - Started process 2721 to run task
[2022-06-02 09:45:11,519] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'YFinance_Crawler_DAG', 'CopyFromLocal', '2022-06-02T09:45:00.307384+00:00', '--job-id', '128', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/Crawler.py', '--cfg-path', '/tmp/tmp7ssquuge']
[2022-06-02 09:45:11,520] {standard_task_runner.py:76} INFO - Job 128: Subtask CopyFromLocal
[2022-06-02 09:45:11,641] {logging_mixin.py:103} INFO - Running <TaskInstance: YFinance_Crawler_DAG.CopyFromLocal 2022-06-02T09:45:00.307384+00:00 [running]> on host slave03
[2022-06-02 09:45:11,921] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=YFinance_Crawler_DAG
AIRFLOW_CTX_TASK_ID=CopyFromLocal
AIRFLOW_CTX_EXECUTION_DATE=2022-06-02T09:45:00.307384+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-02T09:45:00.307384+00:00
[2022-06-02 09:45:11,922] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-06-02 09:45:11,922] {bash.py:158} INFO - Running command: hdfs dfs -mv /opt/flume/current/source1_workdir /user/hadoop/flume/ticker_csv
[2022-06-02 09:45:11,930] {bash.py:169} INFO - Output:
[2022-06-02 09:45:14,008] {bash.py:173} INFO - mv: `/opt/flume/current/source1_workdir': No such file or directory
[2022-06-02 09:45:14,356] {bash.py:177} INFO - Command exited with return code 1
[2022-06-02 09:45:14,382] {taskinstance.py:1396} ERROR - Bash command failed. The command returned a non-zero exit code.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/usr/local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/usr/local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.6/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-06-02 09:45:14,384] {taskinstance.py:1440} INFO - Marking task as FAILED. dag_id=YFinance_Crawler_DAG, task_id=CopyFromLocal, execution_date=20220602T094500, start_date=20220602T094511, end_date=20220602T094514
[2022-06-02 09:45:14,471] {local_task_job.py:118} INFO - Task exited with return code 1
