[2022-06-01 05:30:12,243] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ClusterStartUp.dnstarts02 2022-06-01T05:29:13.040634+00:00 [queued]>
[2022-06-01 05:30:12,282] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ClusterStartUp.dnstarts02 2022-06-01T05:29:13.040634+00:00 [queued]>
[2022-06-01 05:30:12,283] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-06-01 05:30:12,283] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2022-06-01 05:30:12,283] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-06-01 05:30:12,336] {taskinstance.py:1038} INFO - Executing <Task(BashOperator): dnstarts02> on 2022-06-01T05:29:13.040634+00:00
[2022-06-01 05:30:12,340] {standard_task_runner.py:51} INFO - Started process 85 to run task
[2022-06-01 05:30:12,345] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'ClusterStartUp', 'dnstarts02', '2022-06-01T05:29:13.040634+00:00', '--job-id', '69', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ClusterStartUp.py', '--cfg-path', '/tmp/tmpktt789lw']
[2022-06-01 05:30:12,345] {standard_task_runner.py:76} INFO - Job 69: Subtask dnstarts02
[2022-06-01 05:30:12,522] {logging_mixin.py:103} INFO - Running <TaskInstance: ClusterStartUp.dnstarts02 2022-06-01T05:29:13.040634+00:00 [running]> on host slave02
[2022-06-01 05:30:12,690] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=ClusterStartUp
AIRFLOW_CTX_TASK_ID=dnstarts02
AIRFLOW_CTX_EXECUTION_DATE=2022-06-01T05:29:13.040634+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-01T05:29:13.040634+00:00
[2022-06-01 05:30:12,690] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-06-01 05:30:12,691] {bash.py:158} INFO - Running command: $HADOOP_HOME/bin/hdfs --daemon start datanode
[2022-06-01 05:30:12,700] {bash.py:169} INFO - Output:
[2022-06-01 05:30:12,779] {bash.py:173} INFO - WARNING: /opt/hadoop/current/pids does not exist. Creating.
[2022-06-01 05:30:12,784] {bash.py:173} INFO - WARNING: /opt/hadoop/current/logs does not exist. Creating.
[2022-06-01 05:30:14,835] {bash.py:177} INFO - Command exited with return code 0
[2022-06-01 05:30:14,956] {taskinstance.py:1142} INFO - Marking task as SUCCESS. dag_id=ClusterStartUp, task_id=dnstarts02, execution_date=20220601T052913, start_date=20220601T053012, end_date=20220601T053014
[2022-06-01 05:30:15,075] {taskinstance.py:1195} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-06-01 05:30:15,102] {local_task_job.py:118} INFO - Task exited with return code 0
