[2022-06-01 05:30:20,467] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ClusterStartUp.startyarn01 2022-06-01T05:29:13.040634+00:00 [queued]>
[2022-06-01 05:30:20,517] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ClusterStartUp.startyarn01 2022-06-01T05:29:13.040634+00:00 [queued]>
[2022-06-01 05:30:20,517] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-06-01 05:30:20,517] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2022-06-01 05:30:20,517] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-06-01 05:30:20,538] {taskinstance.py:1038} INFO - Executing <Task(BashOperator): startyarn01> on 2022-06-01T05:29:13.040634+00:00
[2022-06-01 05:30:20,541] {standard_task_runner.py:51} INFO - Started process 731 to run task
[2022-06-01 05:30:20,545] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'ClusterStartUp', 'startyarn01', '2022-06-01T05:29:13.040634+00:00', '--job-id', '71', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ClusterStartUp.py', '--cfg-path', '/tmp/tmp_cfovr3u']
[2022-06-01 05:30:20,546] {standard_task_runner.py:76} INFO - Job 71: Subtask startyarn01
[2022-06-01 05:30:20,709] {logging_mixin.py:103} INFO - Running <TaskInstance: ClusterStartUp.startyarn01 2022-06-01T05:29:13.040634+00:00 [running]> on host master01
[2022-06-01 05:30:20,787] {taskinstance.py:1396} ERROR - start-yarn.sh
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/usr/local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1224, in _prepare_and_execute_task_with_callbacks
    self.render_templates(context=context)
  File "/usr/local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1684, in render_templates
    self.task.render_template_fields(context)
  File "/usr/local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 857, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/usr/local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 870, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/usr/local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 905, in render_template
    return jinja_env.get_template(content).render(**context)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.6/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.6/site-packages/jinja2/loaders.py", line 197, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: start-yarn.sh
[2022-06-01 05:30:20,789] {taskinstance.py:1440} INFO - Marking task as FAILED. dag_id=ClusterStartUp, task_id=startyarn01, execution_date=20220601T052913, start_date=20220601T053020, end_date=20220601T053020
[2022-06-01 05:30:20,878] {local_task_job.py:118} INFO - Task exited with return code 1
